project:
  type: book

book:
  title: "metodos_quantitativos"
  author: "Carlos Gutierrez"
  date: "26/02/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - aula01.qmd
    - aula02.qmd
    - aula03.qmd
    - aula04.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

